version: '3.8'

services:
  php-fpm:
    image: php:8.1-fpm
    volumes:
      - ./dist:/var/www/html
      - ./conf.d:/usr/local/etc/php/conf.d

  nginx:
    image: nginx:latest
    ports:
      - "4444:4444"
    volumes:
      - ./dist:/var/www/html
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm