name: Deploy Vite App

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Install node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'
            - name: Install dependencies
              run: npm install
            - name: Build project
              run: npm run build
            - name: Save SSH private key to file
              run: |
                - mkdir -p ~/.ssh
                - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                - chmod 700 ~/.ssh
                - chmod 600 ~/.ssh/id_rsa
            - name: Deploy to server
              run: |
                echo "Deploying to server..."
                scp -r -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -P ${{ secrets.SERVER_PORT || 22 }} dist/* ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/www
                rm ~/.ssh/id_rsa
